# Get all books
Get http://localhost:3000/books HTTP/1.1
Content-Type: application/json

###

# Create a books

POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Potter",
}

###

# Update a books

PUT http://localhost:3000/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Dark Tower"
}

###

# Delete a books

DELETE http://localhost:3000/books/1 HTTP/1.1
Content-Type: application/json

